### ISSUE TITLE
Add new profile

### ISSUE THREAD

**Issue by akirashoyaxx** [fluxfolio/fluxfolio#14]
Add new profile feature that able to click add new profile.

**Comment by thiti-y** [comment]
@akirashoyaxx อันนี้คือทําอะไรหรอ

**Comment by akirashoyaxx** [comment]
> @akirashoyaxx อันนี้คือทําอะไรหรอ น่าจะซำ้กับอันนี้ป่าว #6

เพิ่มและแก้ไข Profile น่าจะเหลือเพิ่ม Profile นะ
